apiVersion: v1
kind: Service
metadata:
  name: gitops-app-service
  labels:
    app: gitops-app 
spec:
  selector:
    app: gitops-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
